### ISSUE TITLE
Preallocation Tracking Before Preorder Period

### ISSUE THREAD

**Issue by Siouxxanne** [Comics-Games-and-Things-LLC/openCGaT#105]
If a cart is manually submitted at the point of sale before the start date of the preorder period for a product, it does not subtract the items from the preallocation number

**Comment by nstephenh** [comment]
It is probably using logic of "is preorder" instead of "is before release
date", I'll try to replace that.

**Comment by nstephenh** [comment]
Pretty sure I got it, just need to test it.
