### ISSUE TITLE
500 Error during Intake

### ISSUE THREAD

**Issue by Siouxxanne** [Comics-Games-and-Things-LLC/openCGaT#118]
Trying to intake a Weapon X & Maverick item via the intake. It is successfully adding it into the purchase order, but not printing a label or inventory. This is the first copy of the item that is not backorder and should be intook normally. Does not occur with view details

**Comment by nstephenh** [comment]
File "/app/intake/views.py", line 96, in intake_item_view
    cart_line_marked_ready = try_mark_cart_line_ready(local_item)
  File "/app/intake/views.py", line 150, in try_mark_cart_line_ready
    if line.quantity > 1:
