### ISSUE TITLE
POS Email Case Sensitive

### ISSUE THREAD

**Issue by Siouxxanne** [Comics-Games-and-Things-LLC/openCGaT#48]
Emails entered in the POS are case sensitive and will not link the cart to an account if the capitalization is different than listed on the account

**Comment by nstephenh** [comment]
It sounds like, while 90% of emails can be not case sensitive, some email providers can, so making email not case sensitive is a security risk.

**Comment by Siouxxanne** [comment]
POS now searches for accounts based on email so carts can be linked to accounts directly
