### ISSUE TITLE
No Watermarking Code?

### ISSUE THREAD

**Issue by reneroth** [Comics-Games-and-Things-LLC/openCGaT#53]
CGaT used to and PWG currently features a watermarking logic where downloaded `.obj` files are watermarked not only by appending a comment at the end, but also by some clever logic that somehow encodes the user ID into the vertex data of the 3d file itself.

This seems to be missing from this here open source codebase, and I really wanted to take a look at the unobfuscated code :) seems like a really clever algorithm that could be used in a lot of places (for example shifting pixel data, pitch in mp3s...).

**Comment by nstephenh** [comment]
That code is now the intellectual property of Printed Wargames. I sold it to them when the platforms split, along with the Patreon integration code. Those were the two big differences, and that, combined with general cleanup and ensuring there weren't any credentials that could leak in the old revision history, are why this repo started fresh.

I'm sure similar techniques could be done on other file types.

**Comment by reneroth** [comment]
Thank you for the information! Should you ever do a writeup/blogpost on the technical details behind it, I'd be highly interested, it's a really cool concept. Hats off to you!
